apiVersion: v1
kind: Pod
metadata:
  name: po2
  labels:
    color: blue
  namespace: brk
spec:
  containers:
    - 
      name: webserver1
      image: httpd:alpine
      ports: 
        -
          containerPort: 80
          hostPort: 8080
      volumeMounts:
        -
          mountPath: /usr/local/apache2/htdocs/
          name: apache-vol
  volumes:
    -
      name: apache-vol
      hostPath:
        path: /Users/bharathreddy/Desktop/BRK/kubetest/kubeflow-experiments/webpage/



    
