apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-example
spec:
  selector:
    matchLabels:
      app: daemonset-example
  template:
    metadata:
      labels:
        app: daemonset-example
    spec:
      containers:
      # This container is run once on each Node in the cluster
        - 
          name: daemonset-example
          image: ubuntu:trusty
          command:
            - 
              /bin/sh
          args:
          - -c
          # This script is run through `sh -c <script>`
          - >-
            while [ true ]; do
            echo "DaemonSet running on $(hostname)" ;
            sleep 10 ;
            done
