apiVersion: autoscaling/v1 #note the autoscaling in api version
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: brk
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: Deployments
    name: php-apache
  targetCPUUtilizationPercentage: 10
    
    
      
  
