apiVersion: v1
kind: Pod
metadata:
  name: po1
  labels:
    color: blue
  namespace: brk
spec:
  containers:
    - 
      name: webserver1
      image: httpd:alpine
      ports: 
        -
          containerPort: 80
      env:
        -
          name: containerKey
          valueFrom: 
            configMapKeyRef:
              key: key1
              name: example-config
