apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: brk
  labels:
    app: sql
  name: brk-sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sql
    spec:
      containers:
        - 
          image: docker.io/mysql:latest
          name: mysql
          env:
            -
              name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: 
                  key: mypass
                  name: sql-secret
            -
              name: MYSQL_DATABASE
              value: brk_db
          resources: {}
status: {}
