apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: brk
  labels:
    app: sql
  name: brk-sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  strategy: {}
  template:
    metadata:
      namespace: brk
      labels:
        app: sql
    spec:
      containers:
        - 
          image: docker.io/mysql:latest
          name: mysql
          envFrom: 
            -
              configMapRef: 
                name: sql-cm
          resources: {}
status: {}
