apiVersion: v1
kind: Pod
metadata:
  name: git-nginx
  labels:
    pur: webserver
  namespace: brk  
spec:
  containers:
    - name: webserver
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: webpage-git
  initContainers:
    - name: init-container
      image: bitnami/git
      volumeMounts:
      - mountPath: /temporary
        name: webpage-git
      command: ["git","clone","https://github.com/bharathkreddy/personal-website-nginx.git","/temporary"]
  volumes: 
    - emptyDir: {}
      name: webpage-git
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    purpose: svc
  namespace: brk
spec:
  ports: 
    -
      port: 30000 #port of the service
      targetPort: 80 # port of the containers it selects from
  selector:
    pur: webserver
  type: NodePort
