apiVersion: v1
kind: Pod
metadata:
  name: po3
  labels:
    color: blue
  namespace: brk
spec:
  containers:
    - 
      name: webserver1
      image: httpd:alpine
      ports: 
        -
          containerPort: 80

