apiVersion: v1
kind: Service
metadata:
  name: svc1
  labels:
    color: red
  namespace: brk
spec:
  ports: 
    -
      port: 5000 #port of the service
      targetPort: 80 # port of the containers it selects from
  selector:
    color: blue
  type: NodePort